[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "ffmpeg"
]

[phases.install]
cmds = [
  "python3.11 -m ensurepip",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "python3.11 app.py"
