[phases.setup]
nixPkgs = ["python311", "ffmpeg"]

[phases.install]
cmds = ["python3.11 -m ensurepip", "pip3 install --upgrade pip", "pip3 install -r requirements.txt"]

[start]
cmd = "python3.11 app.py"
